name: Run Bot for 10 Minutes (Password Protected)

on:
  workflow_dispatch:
    inputs:
      input_password:
        description: "Enter bot password"
        required: true
        type: string

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Mask password input
        run: |
          SECRET_INPUT=$(jq -r '.inputs.input_password' $GITHUB_EVENT_PATH)
          echo "::add-mask::$SECRET_INPUT"
          echo "INPUT_PASSWORD=$SECRET_INPUT" >> $GITHUB_ENV

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run bot
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT: ${{ secrets.TELEGRAM_CHAT }}
          WS_URL: ${{ secrets.WS_URL }}
          BOT_PASSWORD: ${{ secrets.BOT_PASSWORD }}
          INPUT_PASSWORD: ${{ env.INPUT_PASSWORD }}
        run: python bot.py
