name: Run Bot for 10 Minutes

on:
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install websocket-client requests

      - name: Run bot
        env:
          TELEGRAM_CHAT: ${{ secrets.TELEGRAM_CHAT }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          WS_URL: ${{ secrets.WS_URL }}
        run: python main.py
